version: '3.8'
services:
  react-app:
    build: .
    ports:
      - "3001:3000"
    restart: unless-stopped
    container_name: jenkins-test-project-react-app-1
    environment:
      - NODE_ENV=production
